spring.application.name=RainLog

spring.datasource.url=jdbc:postgresql://dpg-d7mnd0m7r5hc738a2h0g-a:5432/rainlog_db
spring.datasource.username=rainlog_db_user
spring.datasource.password=kv0tTzW8443mFr4SdpKEgnAju0cHEbQQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}